### ISSUE TITLE
Instance registration conditions

### ISSUE THREAD

**Issue by fu-sen** [transfem-org/jskapi#1]
Hi. I learned about the existence of Sharkey and have high hopes for it, so I built a Japanese instance.
https://sha.bal.ovh/

Is the registration condition for joinsharkey an instance that users can register?
Since I found out that this web is a derivative of Join Misskey, I could also do a Pull Request.

**Comment by Mar0xy** [comment]
You can find the conditions on the JoinSharkey repo: https://github.com/transfem-org/JoinSharkey/blob/main/SERVER_GUIDELINES.md

**Comment by Insert5StarName** [comment]
@fu-sen  please use the stable branch instead of develop, develop is our testing branch running on https://dev.joinsharkey.org and should not be used on normal instances

**Comment by fu-sen** [comment]
> @fu-sen please use the stable branch instead of develop, develop is our testing branch running on https://dev.joinsharkey.org and should not be used on normal instances
> 
> tho at this point i would suggest waiting till the next stable release and then switch branch

I understand the changes in Misskey 2023.10, and Misskey is aware of the problems that occurred when updating from 2023.9 to 2013.10. Therefore, I deliberately applied Sharkey instance construction in 2023.10. I will wait for stable to be 2023.10 and make my instance stable.

**Comment by Insert5StarName** [comment]
> > @fu-sen please use the stable branch instead of develop, develop is our testing branch running on https://dev.joinsharkey.org and should not be used on normal instances
> > tho at this point i would suggest waiting till the next stable release and then switch branch
> 
> I understand the changes in Misskey 2023.10, and Misskey is aware of the problems that occurred when updating from 2023.9 to 2013.10. Therefore, I deliberately applied Sharkey instance construction in 2023.10. I will wait for stable to be 2023.10 and make my instance stable.

ok if you want to submit your instance please make an issue at https://github.com/transfem-org/JoinSharkey
